# Generated by Django 3.1 on 2021-01-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_restaurant_overall_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='unread_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
