# Generated by Django 3.1 on 2021-01-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_restaurant_unread_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='replies',
            field=models.TextField(null=True),
        ),
    ]
