# Generated by Django 3.1 on 2021-01-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_remove_review_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reply_text',
            field=models.TextField(default=''),
        ),
    ]
